//Extreme values for the different patient posibilities
//Classic patient
#define MAX_CLAS_PROF_SKIN 2
#define MIN_CLAS_PROF_SKIN 1
#define MAX_CLAS_PROF_PERI 8
#define MIN_CLAS_PROF_PERI 6
#define MAX_CLAS_EF_JAUNE_VER 14
#define MIN_CLAS_EF_JAUNE_VER 12
#define MAX_CLAS_EF_INTER_VER 9
#define MIN_CLAS_EF_INTER_VER 8
#define MAX_CLAS_EF_JAUNE 14
#define MIN_CLAS_EF_JAUNE 12
#define MAX_CLAS_EF_INTER 11
#define MIN_CLAS_EF_INTER 10
//Obese patient
#define MAX_OB_PROF_SKIN 4.3
#define MIN_OB_PROF_SKIN 3
#define MAX_OB_PROF_PERI 7
#define MIN_OB_PROF_PERI 5
#define MAX_OB_EF_JAUNE_VER 15
#define MIN_OB_EF_JAUNE_VER 13
#define MAX_OB_EF_INTER_VER 9
#define MIN_OB_EF_INTER_VER 8
#define MAX_OB_EF_JAUNE 15
#define MIN_OB_EF_JAUNE 13
#define MAX_OB_EF_INTER 11
#define MIN_OB_EF_INTER 10
//Clacified patient
#define MAX_CAL_PROF_SKIN 3
#define MIN_CAL_PROF_SKIN 1
#define MAX_CAL_PROF_PERI 7
#define MIN_CAL_PROF_PERI 4
#define MAX_CAL_EF_JAUNE_VER 18
#define MIN_CAL_EF_JAUNE_VER 16
#define MAX_CAL_EF_INTER_VER 10
#define MIN_CAL_EF_INTER_VER 9
#define MAX_CAL_EF_JAUNE 18
#define MIN_CAL_EF_JAUNE 16
#define MAX_CAL_EF_INTER 12
#define MIN_CAL_EF_INTER 11
//Custom patient
#define MAX_CUST_PROF_SKIN 4.3
#define MIN_CUST_PROF_SKIN 1
#define MAX_CUST_PROF_PERI 8
#define MIN_CUST_PROF_PERI 4
#define MAX_CUST_EF_JAUNE_VER 18
#define MIN_CUST_EF_JAUNE_VER 12
#define MAX_CUST_EF_INTER_VER 10
#define MIN_CUST_EF_INTER_VER 8
#define MAX_CUST_EF_JAUNE 18
#define MIN_CUST_EF_JAUNE 12
#define MAX_CUST_EF_INTER 12
#define MIN_CUST_EF_INTER 10
